redis:
  host: localhost
  port: 6379
  db: 0
  username: null
  password: null
  decode_responses: true

redis_wait:
  enabled: false
  replicas: 1
  timeout_ms: 1000

stream_prefixes:
  user_action: stream

stream_read_batch: 100

rdbms:
  retry_attempts: 3
  jdbc:
    host: localhost
    port: 3306
    username: redis
    password: redis
    database: redisdemo

transformations:
  user_action:
    table: user_actions
    mappings:
      user_id: user_id
      action: action
      timestamp: ts

metrics:
  insert_success_stream: stream:insert:success
  insert_failure_stream: stream:insert:failure
  insert_retry_stream: stream:insert:retry
  rdbms_success_stream: stream:rdbms:success
  rdbms_failure_stream: stream:rdbms:failure

  insert_success_counter: metrics:insert:success
  insert_failure_counter: metrics:insert:failure
  insert_retry_counter: metrics:insert:retry
  rdbms_success_counter: metrics:rdbms:success
  rdbms_failure_counter: metrics:rdbms:failure

debug: true
